// Auto-generated by OpenLane
module tbu(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input valid_i,
  input[3:0] dec_bits_i,
  input[7:0] pm_new_s0_i,
  input[7:0] pm_new_s1_i,
  input[7:0] pm_new_s2_i,
  input[7:0] pm_new_s3_i,
  output decoded_bit_o,
  output valid_o
);
endmodule
