// Auto-generated by OpenLane
module sipo(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input data_serial_i,
  input valid_serial_i,
  output[7:0] data_parallel_o,
  output byte_ready_o
);
endmodule
