// Auto-generated by OpenLane
module sync_fifo(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input wr_en_i,
  input[15:0] wr_data_i,
  output full_o,
  input rd_en_i,
  output[15:0] rd_data_o,
  output empty_o
);
endmodule
