// Auto-generated by OpenLane
module bmu(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input[1:0] piso_data_i,
  output[1:0] bm_s0_s0_o,
  output[1:0] bm_s0_s2_o,
  output[1:0] bm_s1_s0_o,
  output[1:0] bm_s1_s2_o,
  output[1:0] bm_s2_s1_o,
  output[1:0] bm_s2_s3_o,
  output[1:0] bm_s3_s1_o,
  output[1:0] bm_s3_s3_o
);
endmodule
