// Auto-generated by OpenLane
module system_top(
`ifdef USE_POWER_PINS
  inout vssd1,
  inout vccd1,
`endif
  input clk,
  input rst_n,
  input dvalid_i,
  input[15:0] data_i,
  output[7:0] data_o,
  output valid_o,
  output busy_o
);
endmodule
