// Auto-generated by OpenLane
module piso(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input[15:0] fifo_data_i,
  input fifo_empty_i,
  output fifo_rd_en_o,
  output[1:0] data_serial_o,
  output valid_serial_o
);
endmodule
