// Auto-generated by OpenLane
module viterbi_core(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input[1:0] piso_data_i,
  input valid_i,
  output core_data_o,
  output core_valid_o
);
endmodule
