// Auto-generated by OpenLane
module pmu(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input valid_i,
  input[7:0] pm_new_s0_i,
  input[7:0] pm_new_s1_i,
  input[7:0] pm_new_s2_i,
  input[7:0] pm_new_s3_i,
  output[7:0] pm_current_s0_o,
  output[7:0] pm_current_s1_o,
  output[7:0] pm_current_s2_o,
  output[7:0] pm_current_s3_o
);
endmodule
